# Generated by Django 5.1 on 2024-09-11 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classification",
            name="order",
            field=models.IntegerField(blank=True, default=0, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="classificationsubclassification",
            unique_together={("classification", "subclassification")},
        ),
    ]
