# Generated by Django 5.1 on 2024-10-16 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movements", "0001_initial"),
        ("profiles", "0009_alter_consentform_reject_reason_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="profilemovement",
            unique_together={("profile", "movement")},
        ),
        migrations.CreateModel(
            name="MovementSyllabusItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "movement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="syllabus_items",
                        to="movements.movement",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="syllabus_assignments",
                        to="movements.movementtopic",
                    ),
                ),
            ],
            options={
                "unique_together": {("movement", "topic")},
            },
        ),
    ]
