# Generated by Django 5.1 on 2024-10-17 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventimage",
            name="primary",
            field=models.BooleanField(default=False),
        ),
    ]
