# Generated by Django 5.1 on 2024-10-17 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_eventimage_primary"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="registration_limit",
        ),
        migrations.AlterField(
            model_name="event",
            name="slug",
            field=models.SlugField(editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="eventimage",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="events.event",
            ),
        ),
    ]
