"""
Constant values for the `activities` app.
"""

ACTIVITY_SUMMARY_MIN_LENGTH = 135
ACTIVITY_SUMMARY_MAX_LENGTH = 300

ACTIVITY_TITLE_MIN_LENGTH = 15
ACTIVITY_TITLE_MAX_LENGTH = 135

ACTIVITY_DEFAULT_REGISTRATION_LIMIT = 50
