# Generated by Django 5.1 on 2024-09-12 14:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mentorships", "0002_mentorship_mentorshipgoal_mentorendorsement_and_more"),
        ("profiles", "0003_alter_discipleship_author_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MentorshipFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("comments", models.TextField()),
                (
                    "rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to="profiles.profile",
                    ),
                ),
                (
                    "mentorship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="mentorships.mentorship",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
