# Generated by Django 5.1 on 2024-09-13 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mentorships", "0003_mentorshipfeedback"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProfileMentorshipAreaInterest",
        ),
    ]
