# Generated by Django 5.1 on 2024-09-30 04:36

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("profiles", "0006_delete_discipleship"),
    ]

    operations = [
        migrations.CreateModel(
            name="Discipleship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "group",
                    models.CharField(
                        choices=[
                            ("group_member", "Group member"),
                            ("first_12", "First 12"),
                            ("first_3", "First 3"),
                            ("sent_forth", "Sent forth"),
                        ],
                        default="group_member",
                        help_text="The group classification of the discipleship (e.g., group_member, group_leader).",
                        max_length=12,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="A unique identifier for the discipleship instance.",
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        help_text="The profile that created this discipleship relationship.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discipleships_created",
                        to="profiles.profile",
                    ),
                ),
                (
                    "disciple",
                    models.ForeignKey(
                        help_text="The profile being discipled.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discipleships_where_disciple",
                        to="profiles.profile",
                    ),
                ),
                (
                    "discipler",
                    models.ForeignKey(
                        help_text="The profile acting as the discipler.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discipleships_where_discipler",
                        to="profiles.profile",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
