# Generated by Django 5.1 on 2024-09-30 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discipleships", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="discipleship",
            name="completed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="The date and time when the discipleship program was completed.",
                null=True,
            ),
        ),
    ]
