# Generated by Django 5.1 on 2024-08-31 04:44

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=255)),
                ("answer", models.TextField()),
            ],
            options={
                "verbose_name_plural": "Frequently asked questions",
            },
        ),
        migrations.CreateModel(
            name="MakeLeaderActionApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action_type",
                    models.CharField(
                        choices=[("change_role_to_leader", "Change role to leader")],
                        default="change_role_to_leader",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "timeout_duration",
                    models.DurationField(default=datetime.timedelta(days=7)),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Setting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "adult_age",
                    models.PositiveIntegerField(
                        default=16,
                        help_text="The age considered as an adult in the application.",
                        verbose_name="Adult Age",
                    ),
                ),
                (
                    "min_registration_age",
                    models.PositiveIntegerField(
                        default=13,
                        help_text="The minimum age required to register in the application.",
                        verbose_name="Minimum Registration Age",
                    ),
                ),
                (
                    "max_mentorship_areas_per_user",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="The maximum number of mentorship areas a user can select.",
                        verbose_name="Maximum Mentorship Areas Per User",
                    ),
                ),
                (
                    "max_active_mentors_per_user",
                    models.PositiveIntegerField(
                        default=3,
                        help_text="The maximum number of active mentors a user can have.",
                        verbose_name="Maximum Active Mentors Per User",
                    ),
                ),
                (
                    "max_active_mentees_per_user",
                    models.PositiveIntegerField(
                        default=3,
                        help_text="The maximum number of active mentees a user can have.",
                        verbose_name="Maximum Active Mentees Per User",
                    ),
                ),
                (
                    "max_skills_per_user",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="The maximum number of skills a user can add.",
                        verbose_name="Maximum Skills Per User",
                    ),
                ),
                (
                    "max_interests_per_user",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="The maximum number of interests a user can add.",
                        verbose_name="Maximum Interests Per User",
                    ),
                ),
                (
                    "max_goals_per_mentorship",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="The maximum number of goals that can be set for a mentorship.",
                        verbose_name="Maximum Goals Per Mentorship",
                    ),
                ),
                (
                    "default_contact_visibility",
                    models.BooleanField(
                        choices=[(True, "Yes"), (False, "No")],
                        default=True,
                        help_text="Determines if the contact information is visible by default.",
                        verbose_name="Default Contact Visibility",
                    ),
                ),
                (
                    "change_role_approval_required",
                    models.BooleanField(
                        choices=[(True, "Yes"), (False, "No")],
                        default=True,
                        help_text="Specifies if approval is required to change a user's role.",
                        verbose_name="Change Role Permission Required",
                    ),
                ),
                (
                    "publish_event_approval_required",
                    models.BooleanField(
                        choices=[(True, "Yes"), (False, "No")],
                        default=True,
                        help_text="Specifies if approval is required to publish an event.",
                        verbose_name="Publish Event Permission Required",
                    ),
                ),
                (
                    "start_mentorship_approval_required",
                    models.BooleanField(
                        choices=[(True, "Yes"), (False, "No")],
                        default=True,
                        help_text="Specifies if approval is required to start a mentorship.",
                        verbose_name="Start Mentorship Permission Required",
                    ),
                ),
                (
                    "add_group_member_approval_required",
                    models.BooleanField(
                        choices=[(True, "Yes"), (False, "No")],
                        default=True,
                        help_text="Specifies if approval is required to add a member to a group.",
                        verbose_name="Add Group Member Permission Required",
                    ),
                ),
                (
                    "publish_testimony_approval_required",
                    models.BooleanField(
                        choices=[(True, "Yes"), (False, "No")],
                        default=True,
                        help_text="Specifies if approval is required to publish a testimony.",
                        verbose_name="Publish Testimony Permission Required",
                    ),
                ),
                (
                    "publish_good_practice_approval_required",
                    models.BooleanField(
                        choices=[(True, "Yes"), (False, "No")],
                        default=True,
                        help_text="Specifies if approval is required to publish a good practice.",
                        verbose_name="Publish Good Practice Permission Required",
                    ),
                ),
                (
                    "publish_prayer_request_approval_required",
                    models.BooleanField(
                        choices=[(True, "Yes"), (False, "No")],
                        default=True,
                        help_text="Specifies if approval is required to publish a prayer request.",
                        verbose_name="Publish Prayer Request Permission Required",
                    ),
                ),
                (
                    "minimum_mentorship_duration_in_weeks",
                    models.PositiveIntegerField(
                        default=4,
                        help_text="The minimum duration in weeks for a mentorship.",
                        verbose_name="Minimum Mentorship Duration (Weeks)",
                    ),
                ),
                (
                    "minimum_mentorship_duration_in_weeks_description",
                    models.CharField(
                        blank=True,
                        help_text="Description of the minimum mentorship duration.",
                        max_length=500,
                        null=True,
                        verbose_name="Minimum Mentorship Duration Description",
                    ),
                ),
                (
                    "max_mentorship_duration_weeks",
                    models.PositiveIntegerField(
                        default=12,
                        help_text="The maximum duration in weeks for a mentorship.",
                        verbose_name="Maximum Mentorship Duration (Weeks)",
                    ),
                ),
                (
                    "min_mentorship_duration_weeks",
                    models.PositiveIntegerField(
                        default=4,
                        help_text="The minimum duration in weeks for a mentorship.",
                        verbose_name="Minimum Mentorship Duration (Weeks)",
                    ),
                ),
                (
                    "mentorship_prohibition_period_weeks",
                    models.PositiveIntegerField(
                        default=4,
                        help_text="The prohibition period in weeks before starting a new mentorship.",
                        verbose_name="Mentorship Prohibition Period (Weeks)",
                    ),
                ),
                (
                    "default_event_registration_limit",
                    models.PositiveIntegerField(
                        default=50,
                        help_text="The default limit for event registrations.",
                        verbose_name="Default Event Registration Limit",
                    ),
                ),
                (
                    "organizer_must_facilitate_training",
                    models.BooleanField(
                        choices=[(True, "Yes"), (False, "No")],
                        default=True,
                        help_text="Specifies if the organizer must facilitate training.",
                        verbose_name="Organizer Must Facilitate Training",
                    ),
                ),
                (
                    "min_days_to_modify_sensitive_content",
                    models.PositiveIntegerField(
                        default=7,
                        help_text="The minimum number of days required to modify sensitive content.",
                        verbose_name="Minimum Days to Modify Sensitive Content",
                    ),
                ),
                (
                    "min_skills_per_training",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="The minimum number of skills required per training.",
                        verbose_name="Minimum Skills Per Training",
                    ),
                ),
                (
                    "max_skills_per_training",
                    models.PositiveIntegerField(
                        default=7,
                        help_text="The maximum number of skills allowed per training.",
                        verbose_name="Maximum Skills Per Training",
                    ),
                ),
            ],
            options={
                "verbose_name": "Setting",
                "verbose_name_plural": "Settings",
            },
        ),
    ]
