# Generated by Django 5.1 on 2024-08-27 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("groups", "0001_initial"),
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="makeleaderactionapproval",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_actions",
                to="profiles.profile",
            ),
        ),
        migrations.AddField(
            model_name="makeleaderactionapproval",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="initiated_approvals",
                to="profiles.profile",
            ),
        ),
        migrations.AddField(
            model_name="makeleaderactionapproval",
            name="group_created_for",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approval_requests",
                to="groups.group",
            ),
        ),
        migrations.AddField(
            model_name="makeleaderactionapproval",
            name="new_leader",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="make_leader_action_approvals",
                to="profiles.profile",
            ),
        ),
    ]
