# Generated by Django 5.1 on 2024-08-19 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="faq",
            options={"verbose_name_plural": "Frequently asked questions"},
        ),
    ]
