# Generated by Django 5.1 on 2024-09-03 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_initial"),
        ("profiles", "0003_alter_discipleship_author_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="makeleaderactionapproval",
            name="read_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approved_actions_read",
                to="profiles.profile",
            ),
        ),
    ]
