# Generated by Django 5.1 on 2024-08-27 11:47

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_setting"),
        ("groups", "0003_alter_group_description"),
        ("profiles", "0013_consentform_reject_reason"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="setting",
            name="add_group_member_permission_required",
        ),
        migrations.RemoveField(
            model_name="setting",
            name="change_role_permission_required",
        ),
        migrations.RemoveField(
            model_name="setting",
            name="publish_event_permission_required",
        ),
        migrations.RemoveField(
            model_name="setting",
            name="publish_good_practice_permission_required",
        ),
        migrations.RemoveField(
            model_name="setting",
            name="publish_prayer_request_permission_required",
        ),
        migrations.RemoveField(
            model_name="setting",
            name="publish_testimony_permission_required",
        ),
        migrations.RemoveField(
            model_name="setting",
            name="start_mentorship_permission_required",
        ),
        migrations.AddField(
            model_name="setting",
            name="add_group_member_approval_required",
            field=models.BooleanField(
                choices=[(True, "Yes"), (False, "No")],
                default=True,
                help_text="Specifies if approval is required to add a member to a group.",
                verbose_name="Add Group Member Permission Required",
            ),
        ),
        migrations.AddField(
            model_name="setting",
            name="change_role_approval_required",
            field=models.BooleanField(
                choices=[(True, "Yes"), (False, "No")],
                default=True,
                help_text="Specifies if approval is required to change a user's role.",
                verbose_name="Change Role Permission Required",
            ),
        ),
        migrations.AddField(
            model_name="setting",
            name="publish_event_approval_required",
            field=models.BooleanField(
                choices=[(True, "Yes"), (False, "No")],
                default=True,
                help_text="Specifies if approval is required to publish an event.",
                verbose_name="Publish Event Permission Required",
            ),
        ),
        migrations.AddField(
            model_name="setting",
            name="publish_good_practice_approval_required",
            field=models.BooleanField(
                choices=[(True, "Yes"), (False, "No")],
                default=True,
                help_text="Specifies if approval is required to publish a good practice.",
                verbose_name="Publish Good Practice Permission Required",
            ),
        ),
        migrations.AddField(
            model_name="setting",
            name="publish_prayer_request_approval_required",
            field=models.BooleanField(
                choices=[(True, "Yes"), (False, "No")],
                default=True,
                help_text="Specifies if approval is required to publish a prayer request.",
                verbose_name="Publish Prayer Request Permission Required",
            ),
        ),
        migrations.AddField(
            model_name="setting",
            name="publish_testimony_approval_required",
            field=models.BooleanField(
                choices=[(True, "Yes"), (False, "No")],
                default=True,
                help_text="Specifies if approval is required to publish a testimony.",
                verbose_name="Publish Testimony Permission Required",
            ),
        ),
        migrations.AddField(
            model_name="setting",
            name="start_mentorship_approval_required",
            field=models.BooleanField(
                choices=[(True, "Yes"), (False, "No")],
                default=True,
                help_text="Specifies if approval is required to start a mentorship.",
                verbose_name="Start Mentorship Permission Required",
            ),
        ),
        migrations.CreateModel(
            name="ActionApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("action_type", models.CharField(max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "timeout_duration",
                    models.DurationField(default=datetime.timedelta(days=7)),
                ),
                ("requires_approval", models.BooleanField(default=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_actions",
                        to="profiles.profile",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_requests",
                        to="groups.group",
                    ),
                ),
                (
                    "initiator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="initiated_approvals",
                        to="profiles.profile",
                    ),
                ),
                (
                    "target_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_targets",
                        to="profiles.profile",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
