# Generated by Django 5.1 on 2024-08-27 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_setting_add_group_member_permission_required_and_more"),
        ("profiles", "0013_consentform_reject_reason"),
    ]

    operations = [
        migrations.RenameField(
            model_name="actionapproval",
            old_name="initiator",
            new_name="created_by",
        ),
        migrations.RenameField(
            model_name="actionapproval",
            old_name="group",
            new_name="group_created_for",
        ),
        migrations.RemoveField(
            model_name="actionapproval",
            name="requires_approval",
        ),
        migrations.RemoveField(
            model_name="actionapproval",
            name="target_profile",
        ),
        migrations.CreateModel(
            name="MakeLeaderActionApproval",
            fields=[
                (
                    "actionapproval_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.actionapproval",
                    ),
                ),
                (
                    "new_leader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="make_leader_action_approvals",
                        to="profiles.profile",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("core.actionapproval",),
        ),
    ]
