# Generated by Django 5.1 on 2024-09-04 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_makeleaderactionapproval_approved_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="makeleaderactionapproval",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
