# Generated by Django 5.1 on 2024-09-23 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_makeleaderactionapproval_approved_at"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MakeLeaderActionApproval",
        ),
    ]
