# Generated by Django 5.1 on 2024-08-27 14:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_rename_initiator_actionapproval_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="actionapproval",
            name="message",
            field=models.TextField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinLengthValidator(100),
                    django.core.validators.MaxLengthValidator(500),
                ],
            ),
        ),
    ]
