# Generated by Django 5.1 on 2024-10-02 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_delete_makeleaderactionapproval"),
    ]

    operations = [
        migrations.AddField(
            model_name="setting",
            name="send_forth_disciple_approval_required",
            field=models.BooleanField(
                choices=[(True, "Yes"), (False, "No")],
                default=True,
                help_text="Specifies if approval is required to send forth a disciple.",
                verbose_name="Send forth disciple permission required",
            ),
        ),
    ]
