# Generated by Django 5.1 on 2024-10-14 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_notification_notificationrecipient_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="delivery_methods",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="expires_at",
        ),
        migrations.AddField(
            model_name="notification",
            name="link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
