# Generated by Django 5.1 on 2024-10-17 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_remove_notification_delivery_methods_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="setting",
            name="default_event_registration_limit",
        ),
    ]
