"""
Constant values for the `events` app.
"""

EVENT_CANCEL_REASON_MIN_LENGTH = 135
EVENT_CANCEL_REASON_MAX_LENGTH = 300

EVENT_SUMMARY_MIN_LENGTH = 135
EVENT_SUMMARY_MAX_LENGTH = 300

EVENT_TITLE_MIN_LENGTH = 15
EVENT_TITLE_MAX_LENGTH = 135

EVENT_DEFAULT_REGISTRATION_LIMIT = 50
