# Generated by Django 5.1 on 2024-09-05 10:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("profiles", "0003_alter_discipleship_author_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(
                        max_length=250,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(3),
                            django.core.validators.RegexValidator(
                                message="Title must not have leading or trailing spaces.",
                                regex="^\\S.*\\S$",
                            ),
                        ],
                    ),
                ),
                ("description", models.TextField()),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vocations_created",
                        to="profiles.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vocation",
                "verbose_name_plural": "Vocations",
            },
        ),
        migrations.CreateModel(
            name="ProfileVocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vocations",
                        to="profiles.profile",
                    ),
                ),
                (
                    "vocation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profiles",
                        to="vocations.vocation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Profile Vocation",
                "verbose_name_plural": "Profile Vocations",
            },
        ),
        migrations.AddIndex(
            model_name="vocation",
            index=models.Index(fields=["title"], name="vocations_v_title_f89f25_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="profilevocation",
            unique_together={("profile", "vocation")},
        ),
    ]
