from django.urls import path

from . import views

app_name = "profiles"

urlpatterns = [
    path(
        "discpleships/<int:discipleship_id>/group-member/",
        views.move_to_group_member,
        name="move_to_group_member",
    ),
    path(
        "discpleships/<int:discipleship_id>/first-12/",
        views.move_to_first_12,
        name="move_to_first_12",
    ),
    path(
        "discpleships/<int:discipleship_id>/first-3/",
        views.move_to_first_3,
        name="move_to_first_3",
    ),
    path(
        "discpleships/<int:discipleship_id>/send-forth/",
        views.move_to_sent_forth,
        name="move_to_sent_forth",
    ),
    path(
        "new/",
        view=views.NewMemberView.as_view(),
        name="register_member",
    ),
    path(
        "<slug:profile_slug>/edit/decrypt",
        views.decrypt_profile,
        name="decrypt_profile",
    ),
    path(
        "<slug:profile_slug>/edit/encrypt",
        views.encrypt_profile,
        name="encrypt_profile",
    ),
    path(
        "<slug:profile_slug>/edit/profile-picture",
        views.edit_profile_picture,
        name="edit_profile_picture",
    ),
    path(
        "<slug:profile_slug>/edit/faith-milestones",
        views.edit_profile_faith_milestones,
        name="edit_profile_faith_milestones",
    ),
    path(
        "<slug:profile_slug>/edit/level",
        views.edit_profile_level,
        name="edit_profile_level",
    ),
    path(
        "<slug:profile_slug>/edit/vocations",
        views.edit_profile_vocations,
        name="edit_profile_vocations",
    ),
    path(
        "<slug:profile_slug>/edit/skills",
        views.edit_profile_skills,
        name="edit_profile_skills",
    ),
    path(
        "<slug:profile_slug>/edit/involvement-details",
        views.edit_involvement_details,
        name="edit_involvement_details",
    ),
    path(
        "<slug:profile_slug>/edit/contact-details",
        views.edit_contact_details,
        name="edit_contact_details",
    ),
    path(
        "<slug:profile_slug>/edit/bio-details",
        views.edit_bio_details,
        name="edit_bio_details",
    ),
    path(
        "<slug:profile_slug>/make-leader-page",
        views.make_leader_page,
        name="make_leader_page",
    ),
    path(
        "<slug:profile_slug>/make-leader",
        views.make_leader,
        name="make_leader",
    ),
    path(
        "<slug:profile_slug>/activities",
        views.profile_activities,
        name="profile_activities",
    ),
    path(
        "<slug:profile_slug>/upload-consent",
        views.upload_consent_form,
        name="upload_consent_form",
    ),
    path(
        "<slug:profile_slug>/settings",
        views.profile_settings,
        name="profile_settings",
    ),
    path(
        "<slug:profile_slug>/trainings",
        views.profile_trainings,
        name="profile_trainings",
    ),
    path(
        "<slug:profile_slug>/involvements",
        views.profile_involvements,
        name="profile_involvements",
    ),
    path(
        "<slug:profile_slug>/discipleships",
        views.profile_discipleships,
        name="profile_discipleships",
    ),
    path(
        "<slug:profile_slug>/levels",
        views.profile_levels,
        name="profile_levels",
    ),
    path(
        "<slug:profile_slug>/",
        views.profile_overview,
        name="profile_overview",
    ),
    path(
        "",
        views.index,
        name="index",
    ),
]
