from django.urls import path

from . import views

app_name = "profiles"

urlpatterns = [
    path(
        "new/",
        view=views.NewMemberView.as_view(),
        name="register_member",
    ),
    path(
        "<slug:profile_slug>/edit/profile-picture",
        views.edit_profile_picture,
        name="edit_profile_picture",
    ),
    path(
        "<slug:profile_slug>/edit/skills",
        views.edit_profile_skills,
        name="edit_profile_skills",
    ),
    path(
        "<slug:profile_slug>/edit/involvement-details",
        views.edit_involvement_details,
        name="edit_involvement_details",
    ),
    path(
        "<slug:profile_slug>/edit/contact-details",
        views.edit_contact_details,
        name="edit_contact_details",
    ),
    path(
        "<slug:profile_slug>/edit/bio-details",
        views.edit_bio_details,
        name="edit_bio_details",
    ),
    path(
        "<slug:profile_slug>/make-leader-page",
        views.make_leader_page,
        name="make_leader_page",
    ),
    path(
        "<slug:profile_slug>/make-leader",
        views.make_leader,
        name="make_leader",
    ),
    path(
        "<slug:profile_slug>/activities",
        views.profile_activities,
        name="profile_activities",
    ),
    path(
        "<slug:profile_slug>/upload-consent",
        views.upload_consent_form,
        name="upload_consent_form",
    ),
    path(
        "<slug:profile_slug>/settings",
        views.profile_settings,
        name="profile_settings",
    ),
    path(
        "<slug:profile_slug>/trainings",
        views.profile_trainings,
        name="profile_trainings",
    ),
    path(
        "<slug:profile_slug>/involvements",
        views.profile_involvements,
        name="profile_involvements",
    ),
    path(
        "<slug:profile_slug>/",
        views.profile_detail,
        name="profile_detail",
    ),
    path(
        "",
        views.index,
        name="index",
    ),
]
