from django.urls import path

from . import views

app_name = "profiles"

urlpatterns = [
    path(
        "new/",
        view=views.NewMemberView.as_view(),
        name="register_member",
    ),
    path(
        "<slug:profile_slug>/edit/decrypt",
        views.decrypt_profile,
        name="decrypt_profile",
    ),
    path(
        "<slug:profile_slug>/edit/encrypt",
        views.encrypt_profile,
        name="encrypt_profile",
    ),
    path(
        "<slug:profile_slug>/edit/profile-picture",
        views.edit_profile_picture,
        name="edit_profile_picture",
    ),
    path(
        "<slug:profile_slug>/edit/faith-milestones",
        views.edit_profile_faith_milestones,
        name="edit_profile_faith_milestones",
    ),
    path(
        "<slug:profile_slug>/edit/level",
        views.edit_profile_level,
        name="edit_profile_level",
    ),
    path(
        "<slug:profile_slug>/edit/edit_profile_classifications/<int:profile_classification_no>",
        views.edit_profile_classifications,
        name="edit_profile_classifications",
    ),
    path(
        "<slug:profile_slug>/edit/vocations",
        views.edit_profile_vocations,
        name="edit_profile_vocations",
    ),
    path(
        "<slug:profile_slug>/edit/skills",
        views.edit_profile_skills,
        name="edit_profile_skills",
    ),
    path(
        "<slug:profile_slug>/edit/involvement-details",
        views.edit_involvement_details,
        name="edit_involvement_details",
    ),
    path(
        "<slug:profile_slug>/edit/contact-details",
        views.edit_contact_details,
        name="edit_contact_details",
    ),
    path(
        "<slug:profile_slug>/edit/bio-details",
        views.edit_bio_details,
        name="edit_bio_details",
    ),
    path(
        "<slug:profile_slug>/edit/mentorship-details",
        views.edit_profile_mentorship_areas,
        name="edit_profile_mentorship_areas",
    ),
    path(
        "<slug:profile_slug>/make-leader-page",
        views.make_leader_page,
        name="make_leader_page",
    ),
    path(
        "<slug:profile_slug>/make-leader",
        views.make_leader,
        name="make_leader",
    ),
    path(
        "<slug:profile_slug>/make-member-page",
        views.make_member_page,
        name="make_member_page",
    ),
    path(
        "<slug:profile_slug>/make-member",
        views.make_member,
        name="make_member",
    ),
    path(
        "<slug:profile_slug>/make-external-page",
        views.make_external_person_page,
        name="make_external_person_page",
    ),
    path(
        "<slug:profile_slug>/make-external",
        views.make_external_person,
        name="make_external_person",
    ),
    path(
        "<slug:profile_slug>/activities",
        views.profile_activities,
        name="profile_activities",
    ),
    path(
        "<slug:profile_slug>/upload-consent",
        views.upload_consent_form,
        name="upload_consent_form",
    ),
    path(
        "<slug:profile_slug>/settings",
        views.profile_settings,
        name="profile_settings",
    ),
    path(
        "<slug:profile_slug>/trainings",
        views.profile_trainings,
        name="profile_trainings",
    ),
    path(
        "<slug:profile_slug>/levels",
        views.profile_levels,
        name="profile_levels",
    ),
    path(
        "<slug:profile_slug>/classifications",
        views.profile_classifications,
        name="profile_classifications",
    ),
    path(
        "<slug:profile_slug>/mentorships",
        views.profile_mentorships,
        name="profile_mentorships",
    ),
    path(
        "<slug:profile_slug>/move-member-to-sister-group/<slug:group_slug>",
        views.move_to_sister_group,
        name="move_to_sister_group",
    ),
    path(
        "<slug:profile_slug>/move-member-to-child-group/<slug:group_slug>",
        views.move_to_child_group,
        name="move_to_child_group",
    ),
    path(
        "<slug:profile_slug>/",
        views.profile_overview,
        name="profile_overview",
    ),
    path(
        "",
        views.index,
        name="index",
    ),
]
