# Generated by Django 5.1 on 2024-08-31 04:44

import uuid

import cloudinary.models
import django.core.validators
import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "location_country",
                    django_countries.fields.CountryField(
                        blank=True, max_length=2, null=True
                    ),
                ),
                (
                    "location_city",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        default=uuid.uuid4,
                        editable=False,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("member", "Member"),
                            ("leader", "Leader"),
                            ("external_person", "External Person"),
                        ],
                        default="member",
                        max_length=20,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        default="default@email.kns", max_length=254, unique=True
                    ),
                ),
                ("last_name", models.CharField(blank=True, max_length=25, null=True)),
                ("first_name", models.CharField(blank=True, max_length=25, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("male", "Male"), ("female", "Female")],
                        default="male",
                        max_length=6,
                        null=True,
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("chat_is_disabled", models.BooleanField(default=False)),
                ("email_notifications", models.BooleanField(default=True)),
                ("display_hints", models.BooleanField(default=True)),
                ("bio_details_is_visible", models.BooleanField(default=True)),
                ("contact_details_is_visible", models.BooleanField(default=True)),
                (
                    "place_of_birth_country",
                    django_countries.fields.CountryField(
                        blank=True, max_length=2, null=True
                    ),
                ),
                (
                    "place_of_birth_city",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("phone", models.CharField(blank=True, max_length=15, null=True)),
                ("phone_prefix", models.CharField(blank=True, max_length=5, null=True)),
                (
                    "is_movement_training_facilitator",
                    models.BooleanField(default=False),
                ),
                (
                    "reason_is_not_movement_training_facilitator",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("is_skill_training_facilitator", models.BooleanField(default=False)),
                (
                    "reason_is_not_skill_training_facilitator",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("is_mentor", models.BooleanField(default=False)),
                (
                    "reason_is_not_mentor",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "email_token",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "image",
                    cloudinary.models.CloudinaryField(
                        blank=True, max_length=255, null=True
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EncryptionReason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=150, unique=True)),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        default=uuid.uuid4,
                        editable=False,
                        null=True,
                        unique=True,
                    ),
                ),
                ("description", models.CharField(max_length=250)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="encryption_reasons_created",
                        to="profiles.profile",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "unique_together": {("title", "slug")},
            },
        ),
        migrations.CreateModel(
            name="ConsentForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "consent_form",
                    cloudinary.models.CloudinaryField(
                        blank=True, max_length=255, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reject_reason",
                    models.TextField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinLengthValidator(100),
                            django.core.validators.MaxLengthValidator(500),
                        ],
                    ),
                ),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consent_form",
                        to="profiles.profile",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_consent_forms",
                        to="profiles.profile",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consent_forms_submitted",
                        to="profiles.profile",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProfileEncryption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_name", models.CharField(max_length=25)),
                ("first_name", models.CharField(max_length=25)),
                (
                    "encrypted_by",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_encryptions",
                        to="profiles.profile",
                    ),
                ),
                (
                    "encryption_reason",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="encryptions",
                        to="profiles.encryptionreason",
                    ),
                ),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="encryption",
                        to="profiles.profile",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
