# Generated by Django 5.1 on 2024-09-02 03:51

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Discipleship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "group",
                    models.CharField(
                        choices=[
                            ("Group member", "Group member"),
                            ("First 12", "First 12"),
                            ("First 3", "First 3"),
                            ("Sent forth", "Sent forth"),
                        ],
                        default="Group member",
                        max_length=12,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        default=uuid.uuid4,
                        editable=False,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discipleships_created",
                        to="profiles.profile",
                    ),
                ),
                (
                    "disciple",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discipleships_where_disciple",
                        to="profiles.profile",
                    ),
                ),
                (
                    "discipler",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discipleships_where_discipler",
                        to="profiles.profile",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
