# Generated by Django 5.1 on 2024-08-30 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_encryptionreason_profileencryption"),
    ]

    operations = [
        migrations.AddField(
            model_name="profileencryption",
            name="encrypted_by",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_encryptions",
                to="profiles.profile",
            ),
        ),
    ]
