# Generated by Django 5.1 on 2024-09-03 09:29

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_discipleship"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discipleship",
            name="author",
            field=models.ForeignKey(
                help_text="The profile that created this discipleship relationship.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="discipleships_created",
                to="profiles.profile",
            ),
        ),
        migrations.AlterField(
            model_name="discipleship",
            name="disciple",
            field=models.ForeignKey(
                help_text="The profile being discipled.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="discipleships_where_disciple",
                to="profiles.profile",
            ),
        ),
        migrations.AlterField(
            model_name="discipleship",
            name="discipler",
            field=models.ForeignKey(
                help_text="The profile acting as the discipler.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="discipleships_where_discipler",
                to="profiles.profile",
            ),
        ),
        migrations.AlterField(
            model_name="discipleship",
            name="group",
            field=models.CharField(
                choices=[
                    ("group_member", "Group member"),
                    ("first_12", "First 12"),
                    ("first_3", "First 3"),
                    ("sent_forth", "Sent forth"),
                ],
                default="group_member",
                help_text="The group classification of the discipleship (e.g., group_member, group_leader).",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="discipleship",
            name="slug",
            field=models.SlugField(
                blank=True,
                default=uuid.uuid4,
                editable=False,
                help_text="A unique identifier for the discipleship instance.",
                null=True,
                unique=True,
            ),
        ),
    ]
