# Generated by Django 5.1 on 2024-08-15 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_profile_created_at_profile_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="agreed_to_terms",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="is_visitor",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="verified",
            field=models.BooleanField(default=False),
        ),
    ]
