# Generated by Django 5.1 on 2024-09-17 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_alter_discipleship_author_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_onboarded",
            field=models.BooleanField(
                choices=[(True, "Yes"), (False, "No")], default=False
            ),
        ),
    ]
