# Generated by Django 5.1 on 2024-09-28 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0004_profile_is_onboarded"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="set_password_token",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
