# Generated by Django 5.1 on 2024-08-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0005_profile_date_of_birth_profile_first_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="agreed_to_terms",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="is_visitor",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="verified",
        ),
        migrations.AddField(
            model_name="profile",
            name="bio_details_is_visible",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="chat_is_disabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="contact_details_is_visible",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="display_hints",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="email_notificaitons",
            field=models.BooleanField(default=True),
        ),
    ]
