# Generated by Django 5.1 on 2024-09-30 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0005_profile_set_password_token"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Discipleship",
        ),
    ]
