# Generated by Django 5.1 on 2024-10-02 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0006_delete_discipleship"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="email_token_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
