# Generated by Django 5.1 on 2024-08-16 12:07

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0006_remove_profile_agreed_to_terms_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="slug",
            field=models.SlugField(
                blank=True, default=uuid.uuid4, editable=False, null=True, unique=True
            ),
        ),
    ]
