# Generated by Django 5.1 on 2024-10-11 09:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0008_alter_profile_reason_is_not_mentor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consentform",
            name="reject_reason",
            field=models.TextField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinLengthValidator(50),
                    django.core.validators.MaxLengthValidator(175),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="reason_is_not_mentor",
            field=models.TextField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinLengthValidator(50),
                    django.core.validators.MaxLengthValidator(175),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="reason_is_not_movement_training_facilitator",
            field=models.TextField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinLengthValidator(50),
                    django.core.validators.MaxLengthValidator(175),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="reason_is_not_skill_training_facilitator",
            field=models.TextField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinLengthValidator(50),
                    django.core.validators.MaxLengthValidator(175),
                ],
            ),
        ),
    ]
