# Generated by Django 5.1 on 2024-08-23 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "profiles",
            "0009_profile_email_token_profile_image_profile_is_mentor_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="email_notificaitons",
            new_name="email_notifications",
        ),
    ]
