# Generated by Django 5.1 on 2024-08-23 12:25

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0010_rename_email_notificaitons_profile_email_notifications"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="location_city",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="location_country",
            field=django_countries.fields.CountryField(
                blank=True, max_length=2, null=True
            ),
        ),
    ]
