# Generated by Django 5.1 on 2024-08-25 03:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0012_consentform"),
    ]

    operations = [
        migrations.AddField(
            model_name="consentform",
            name="reject_reason",
            field=models.TextField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinLengthValidator(100),
                    django.core.validators.MaxLengthValidator(500),
                ],
            ),
        ),
    ]
