# Generated by Django 5.1 on 2024-09-09 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("levels", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profilelevel",
            name="removed_at",
        ),
        migrations.AlterField(
            model_name="levelsublevel",
            name="level",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sublevels",
                to="levels.level",
            ),
        ),
        migrations.AlterField(
            model_name="levelsublevel",
            name="sublevel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="levels",
                to="levels.sublevel",
            ),
        ),
    ]
