# Generated by Django 5.1 on 2024-08-19 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0001_initial"),
        ("profiles", "0007_profile_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupmember",
            name="profile",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group_in",
                to="profiles.profile",
            ),
        ),
    ]
