# Generated by Django 5.1 on 2024-08-23 04:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0002_alter_groupmember_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="description",
            field=models.TextField(
                validators=[
                    django.core.validators.MinLengthValidator(100),
                    django.core.validators.MaxLengthValidator(500),
                ]
            ),
        ),
    ]
