# Generated by Django 5.1 on 2024-09-19 04:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onboarding", "0001_initial"),
        ("profiles", "0004_profile_is_onboarded"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfileCompletion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_completion",
                        to="profiles.profile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProfileCompletionTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "task_name",
                    models.CharField(
                        choices=[
                            ("complete_profile", "Complete your profile"),
                            ("register_group", "Register group"),
                            ("register_first_member", "Register first member"),
                            (
                                "add_vocations_skills",
                                "Add vocations, skills, and interests",
                            ),
                            ("browse_events", "Browse events near you"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "task_description",
                    models.CharField(
                        validators=[
                            django.core.validators.MinLengthValidator(120),
                            django.core.validators.MaxLengthValidator(150),
                        ]
                    ),
                ),
                ("description", models.TextField()),
                ("is_complete", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completion_tasks",
                        to="profiles.profile",
                    ),
                ),
            ],
            options={
                "unique_together": {("profile", "task_name")},
            },
        ),
    ]
