# Generated by Django 5.1 on 2024-09-19 04:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onboarding", "0002_profilecompletion_profilecompletiontask"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profilecompletiontask",
            name="task_description",
            field=models.CharField(
                max_length=150,
                validators=[
                    django.core.validators.MinLengthValidator(120),
                    django.core.validators.MaxLengthValidator(150),
                ],
            ),
        ),
    ]
