# Generated by Django 5.1 on 2024-09-19 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("onboarding", "0003_alter_profilecompletiontask_task_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profilecompletiontask",
            name="description",
        ),
    ]
