# Generated by Django 5.1 on 2024-09-19 09:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onboarding", "0004_remove_profilecompletiontask_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profilecompletiontask",
            name="task_description",
            field=models.TextField(
                validators=[
                    django.core.validators.MinLengthValidator(120),
                    django.core.validators.MaxLengthValidator(150),
                ]
            ),
        ),
    ]
