# Generated by Django 5.1 on 2024-09-19 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onboarding", "0005_alter_profilecompletiontask_task_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="profilecompletiontask",
            name="task_link",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
